version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@0.0.10
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: "AWS_ACCOUNT_ID_ENV_VAR_NAME.dkr.ecr.AWS_DEFAULT_REGION_ENV_VAR_NAME.amazonaws.com"
          repo: "AWS_RESOURCE_NAME_PREFIX_ENV_VAR_NAME"
          region: AWS_DEFAULT_REGION_ENV_VAR_NAME
          tag: "${CIRCLE_SHA1}"
